// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package catalogdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCatalogProducts = `-- name: CountCatalogProducts :one
SELECT COUNT(*)
FROM catalog_products
`

func (q *Queries) CountCatalogProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCatalogProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCatalogProduct = `-- name: CreateCatalogProduct :one
INSERT INTO catalog_products (
    id,
    name,
    description,
    price_cents,
    currency,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (id)
DO UPDATE
SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    price_cents = EXCLUDED.price_cents,
    currency = EXCLUDED.currency,
    updated_at = EXCLUDED.updated_at
RETURNING id, name, description, price_cents, currency, created_at, updated_at
`

type CreateCatalogProductParams struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	PriceCents  int64              `json:"price_cents"`
	Currency    int32              `json:"currency"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCatalogProduct(ctx context.Context, arg CreateCatalogProductParams) (CatalogProduct, error) {
	row := q.db.QueryRow(ctx, createCatalogProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PriceCents,
		arg.Currency,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CatalogProduct
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCatalogProduct = `-- name: DeleteCatalogProduct :one
DELETE FROM catalog_products
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteCatalogProduct(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, deleteCatalogProduct, id)
	err := row.Scan(&id)
	return id, err
}

const getCatalogProductByID = `-- name: GetCatalogProductByID :one
SELECT id, name, description, price_cents, currency, created_at, updated_at
FROM catalog_products
WHERE id = $1
`

func (q *Queries) GetCatalogProductByID(ctx context.Context, id string) (CatalogProduct, error) {
	row := q.db.QueryRow(ctx, getCatalogProductByID, id)
	var i CatalogProduct
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCatalogProducts = `-- name: ListCatalogProducts :many
SELECT id, name, description, price_cents, currency, created_at, updated_at
FROM catalog_products
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListCatalogProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCatalogProducts(ctx context.Context, arg ListCatalogProductsParams) ([]CatalogProduct, error) {
	rows, err := q.db.Query(ctx, listCatalogProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogProduct{}
	for rows.Next() {
		var i CatalogProduct
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PriceCents,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCatalogProduct = `-- name: UpdateCatalogProduct :one
UPDATE catalog_products
SET
    name = $2,
    description = $3,
    price_cents = $4,
    currency = $5,
    updated_at = $6
WHERE id = $1
RETURNING id, name, description, price_cents, currency, created_at, updated_at
`

type UpdateCatalogProductParams struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	PriceCents  int64              `json:"price_cents"`
	Currency    int32              `json:"currency"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateCatalogProduct(ctx context.Context, arg UpdateCatalogProductParams) (CatalogProduct, error) {
	row := q.db.QueryRow(ctx, updateCatalogProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PriceCents,
		arg.Currency,
		arg.UpdatedAt,
	)
	var i CatalogProduct
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
