services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v25.1.4
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092,OUTSIDE://localhost:19092
      - --pandaproxy-addr=PLAINTEXT://0.0.0.0:8082
      - --advertise-pandaproxy-addr=PLAINTEXT://redpanda:8082
      - --set=redpanda.auto_create_topics_enabled=true
    ports:
      - "19092:19092"
      - "9644:9644"
      - "8082:8082"

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:v2.8.2
    depends_on:
      - redpanda
    environment:
      KAFKA_BROKERS: redpanda:9092
    ports:
      - "8081:8080"

  redis:
    image: redis:8.2-alpine
    ports:
      - "6379:6379"
