// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package orderdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID                   string             `json:"id"`
	CustomerID           string             `json:"customer_id"`
	TotalAmountCurrency  string             `json:"total_amount_currency"`
	TotalAmountCents     int64              `json:"total_amount_cents"`
	Status               string             `json:"status"`
	ShippingCountry      string             `json:"shipping_country"`
	ShippingCity         string             `json:"shipping_city"`
	ShippingStreet       string             `json:"shipping_street"`
	ShippingPostalCode   string             `json:"shipping_postal_code"`
	ShippingHouse        string             `json:"shipping_house"`
	ShippingApartment    string             `json:"shipping_apartment"`
	PaymentMethod        string             `json:"payment_method"`
	PaymentMethodDetails string             `json:"payment_method_details"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type OrderItem struct {
	OrderID               string `json:"order_id"`
	ItemPosition          int32  `json:"item_position"`
	ProductID             string `json:"product_id"`
	Sku                   string `json:"sku"`
	ProductName           string `json:"product_name"`
	Quantity              int32  `json:"quantity"`
	UnitPriceCurrency     string `json:"unit_price_currency"`
	UnitPriceAmountCents  int64  `json:"unit_price_amount_cents"`
	TotalPriceCurrency    string `json:"total_price_currency"`
	TotalPriceAmountCents int64  `json:"total_price_amount_cents"`
}
