// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package orderdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID                   string             `json:"id"`
	CustomerID           string             `json:"customer_id"`
	IdempotencyKey       pgtype.Text        `json:"idempotency_key"`
	TotalAmountCurrency  string             `json:"total_amount_currency"`
	TotalAmountCents     int64              `json:"total_amount_cents"`
	Status               string             `json:"status"`
	ShippingCountry      string             `json:"shipping_country"`
	ShippingCity         string             `json:"shipping_city"`
	ShippingStreet       string             `json:"shipping_street"`
	ShippingPostalCode   string             `json:"shipping_postal_code"`
	ShippingHouse        string             `json:"shipping_house"`
	ShippingApartment    string             `json:"shipping_apartment"`
	PaymentMethod        string             `json:"payment_method"`
	PaymentMethodDetails string             `json:"payment_method_details"`
	CancelReason         string             `json:"cancel_reason"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type OrderItem struct {
	OrderID               string `json:"order_id"`
	ItemPosition          int32  `json:"item_position"`
	ProductID             string `json:"product_id"`
	Sku                   string `json:"sku"`
	ProductName           string `json:"product_name"`
	Quantity              int32  `json:"quantity"`
	UnitPriceCurrency     string `json:"unit_price_currency"`
	UnitPriceAmountCents  int64  `json:"unit_price_amount_cents"`
	TotalPriceCurrency    string `json:"total_price_currency"`
	TotalPriceAmountCents int64  `json:"total_price_amount_cents"`
}

type OrderOutboxEvent struct {
	ID            string             `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	Topic         string             `json:"topic"`
	EventKey      string             `json:"event_key"`
	Payload       []byte             `json:"payload"`
	AttemptCount  int32              `json:"attempt_count"`
	LastError     string             `json:"last_error"`
	LockedAt      pgtype.Timestamptz `json:"locked_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
}
