// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package orderdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingOrderOutboxEvents = `-- name: ClaimPendingOrderOutboxEvents :many
WITH pending AS (
    SELECT id
    FROM order_outbox_events AS pending_events
    WHERE pending_events.published_at IS NULL
      AND (pending_events.locked_at IS NULL OR pending_events.locked_at < $2)
    ORDER BY pending_events.created_at ASC
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
UPDATE order_outbox_events AS o
SET locked_at = $3
FROM pending
WHERE o.id = pending.id
RETURNING o.id, o.aggregate_type, o.aggregate_id, o.event_type, o.topic, o.event_key, o.payload, o.attempt_count, o.last_error, o.locked_at, o.created_at, o.published_at
`

type ClaimPendingOrderOutboxEventsParams struct {
	Limit      int32              `json:"limit"`
	LockedAt   pgtype.Timestamptz `json:"locked_at"`
	LockedAt_2 pgtype.Timestamptz `json:"locked_at_2"`
}

func (q *Queries) ClaimPendingOrderOutboxEvents(ctx context.Context, arg ClaimPendingOrderOutboxEventsParams) ([]OrderOutboxEvent, error) {
	rows, err := q.db.Query(ctx, claimPendingOrderOutboxEvents, arg.Limit, arg.LockedAt, arg.LockedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderOutboxEvent{}
	for rows.Next() {
		var i OrderOutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Topic,
			&i.EventKey,
			&i.Payload,
			&i.AttemptCount,
			&i.LastError,
			&i.LockedAt,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOrdersByCustomer = `-- name: CountOrdersByCustomer :one
SELECT COUNT(*)
FROM orders
WHERE customer_id = $1
`

func (q *Queries) CountOrdersByCustomer(ctx context.Context, customerID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByCustomer, customerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    id,
    customer_id,
    idempotency_key,
    total_amount_currency,
    total_amount_cents,
    status,
    shipping_country,
    shipping_city,
    shipping_street,
    shipping_postal_code,
    shipping_house,
    shipping_apartment,
    payment_method,
    payment_method_details,
    cancel_reason,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
)
RETURNING id, customer_id, idempotency_key, total_amount_currency, total_amount_cents, status, shipping_country, shipping_city, shipping_street, shipping_postal_code, shipping_house, shipping_apartment, payment_method, payment_method_details, cancel_reason, created_at, updated_at
`

type CreateOrderParams struct {
	ID                   string             `json:"id"`
	CustomerID           string             `json:"customer_id"`
	IdempotencyKey       pgtype.Text        `json:"idempotency_key"`
	TotalAmountCurrency  string             `json:"total_amount_currency"`
	TotalAmountCents     int64              `json:"total_amount_cents"`
	Status               string             `json:"status"`
	ShippingCountry      string             `json:"shipping_country"`
	ShippingCity         string             `json:"shipping_city"`
	ShippingStreet       string             `json:"shipping_street"`
	ShippingPostalCode   string             `json:"shipping_postal_code"`
	ShippingHouse        string             `json:"shipping_house"`
	ShippingApartment    string             `json:"shipping_apartment"`
	PaymentMethod        string             `json:"payment_method"`
	PaymentMethodDetails string             `json:"payment_method_details"`
	CancelReason         string             `json:"cancel_reason"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.CustomerID,
		arg.IdempotencyKey,
		arg.TotalAmountCurrency,
		arg.TotalAmountCents,
		arg.Status,
		arg.ShippingCountry,
		arg.ShippingCity,
		arg.ShippingStreet,
		arg.ShippingPostalCode,
		arg.ShippingHouse,
		arg.ShippingApartment,
		arg.PaymentMethod,
		arg.PaymentMethodDetails,
		arg.CancelReason,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.IdempotencyKey,
		&i.TotalAmountCurrency,
		&i.TotalAmountCents,
		&i.Status,
		&i.ShippingCountry,
		&i.ShippingCity,
		&i.ShippingStreet,
		&i.ShippingPostalCode,
		&i.ShippingHouse,
		&i.ShippingApartment,
		&i.PaymentMethod,
		&i.PaymentMethodDetails,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO order_items (
    order_id,
    item_position,
    product_id,
    sku,
    product_name,
    quantity,
    unit_price_currency,
    unit_price_amount_cents,
    total_price_currency,
    total_price_amount_cents
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
`

type CreateOrderItemParams struct {
	OrderID               string `json:"order_id"`
	ItemPosition          int32  `json:"item_position"`
	ProductID             string `json:"product_id"`
	Sku                   string `json:"sku"`
	ProductName           string `json:"product_name"`
	Quantity              int32  `json:"quantity"`
	UnitPriceCurrency     string `json:"unit_price_currency"`
	UnitPriceAmountCents  int64  `json:"unit_price_amount_cents"`
	TotalPriceCurrency    string `json:"total_price_currency"`
	TotalPriceAmountCents int64  `json:"total_price_amount_cents"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.Exec(ctx, createOrderItem,
		arg.OrderID,
		arg.ItemPosition,
		arg.ProductID,
		arg.Sku,
		arg.ProductName,
		arg.Quantity,
		arg.UnitPriceCurrency,
		arg.UnitPriceAmountCents,
		arg.TotalPriceCurrency,
		arg.TotalPriceAmountCents,
	)
	return err
}

const createOrderOutboxEvent = `-- name: CreateOrderOutboxEvent :exec
INSERT INTO order_outbox_events (
    id,
    aggregate_type,
    aggregate_id,
    event_type,
    topic,
    event_key,
    payload,
    attempt_count,
    last_error,
    locked_at,
    created_at,
    published_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
`

type CreateOrderOutboxEventParams struct {
	ID            string             `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	Topic         string             `json:"topic"`
	EventKey      string             `json:"event_key"`
	Payload       []byte             `json:"payload"`
	AttemptCount  int32              `json:"attempt_count"`
	LastError     string             `json:"last_error"`
	LockedAt      pgtype.Timestamptz `json:"locked_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) CreateOrderOutboxEvent(ctx context.Context, arg CreateOrderOutboxEventParams) error {
	_, err := q.db.Exec(ctx, createOrderOutboxEvent,
		arg.ID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Topic,
		arg.EventKey,
		arg.Payload,
		arg.AttemptCount,
		arg.LastError,
		arg.LockedAt,
		arg.CreatedAt,
		arg.PublishedAt,
	)
	return err
}

const deleteOrderItemsByOrderID = `-- name: DeleteOrderItemsByOrderID :exec
DELETE FROM order_items
WHERE order_id = $1
`

func (q *Queries) DeleteOrderItemsByOrderID(ctx context.Context, orderID string) error {
	_, err := q.db.Exec(ctx, deleteOrderItemsByOrderID, orderID)
	return err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, customer_id, idempotency_key, total_amount_currency, total_amount_cents, status, shipping_country, shipping_city, shipping_street, shipping_postal_code, shipping_house, shipping_apartment, payment_method, payment_method_details, cancel_reason, created_at, updated_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.IdempotencyKey,
		&i.TotalAmountCurrency,
		&i.TotalAmountCents,
		&i.Status,
		&i.ShippingCountry,
		&i.ShippingCity,
		&i.ShippingStreet,
		&i.ShippingPostalCode,
		&i.ShippingHouse,
		&i.ShippingApartment,
		&i.PaymentMethod,
		&i.PaymentMethodDetails,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByIdempotencyKey = `-- name: GetOrderByIdempotencyKey :one
SELECT id, customer_id, idempotency_key, total_amount_currency, total_amount_cents, status, shipping_country, shipping_city, shipping_street, shipping_postal_code, shipping_house, shipping_apartment, payment_method, payment_method_details, cancel_reason, created_at, updated_at
FROM orders
WHERE idempotency_key = $1
`

func (q *Queries) GetOrderByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByIdempotencyKey, idempotencyKey)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.IdempotencyKey,
		&i.TotalAmountCurrency,
		&i.TotalAmountCents,
		&i.Status,
		&i.ShippingCountry,
		&i.ShippingCity,
		&i.ShippingStreet,
		&i.ShippingPostalCode,
		&i.ShippingHouse,
		&i.ShippingApartment,
		&i.PaymentMethod,
		&i.PaymentMethodDetails,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderOutboxStats = `-- name: GetOrderOutboxStats :one
SELECT
    COUNT(*) FILTER (WHERE published_at IS NULL) AS pending_count,
    COUNT(*) FILTER (WHERE published_at IS NULL AND attempt_count > 0) AS retrying_count,
    MIN(created_at) FILTER (WHERE published_at IS NULL) AS oldest_pending_created_at
FROM order_outbox_events
`

type GetOrderOutboxStatsRow struct {
	PendingCount           int64       `json:"pending_count"`
	RetryingCount          int64       `json:"retrying_count"`
	OldestPendingCreatedAt interface{} `json:"oldest_pending_created_at"`
}

func (q *Queries) GetOrderOutboxStats(ctx context.Context) (GetOrderOutboxStatsRow, error) {
	row := q.db.QueryRow(ctx, getOrderOutboxStats)
	var i GetOrderOutboxStatsRow
	err := row.Scan(&i.PendingCount, &i.RetryingCount, &i.OldestPendingCreatedAt)
	return i, err
}

const listOrderItemsByOrderID = `-- name: ListOrderItemsByOrderID :many
SELECT order_id, item_position, product_id, sku, product_name, quantity, unit_price_currency, unit_price_amount_cents, total_price_currency, total_price_amount_cents
FROM order_items
WHERE order_id = $1
ORDER BY item_position ASC
`

func (q *Queries) ListOrderItemsByOrderID(ctx context.Context, orderID string) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.OrderID,
			&i.ItemPosition,
			&i.ProductID,
			&i.Sku,
			&i.ProductName,
			&i.Quantity,
			&i.UnitPriceCurrency,
			&i.UnitPriceAmountCents,
			&i.TotalPriceCurrency,
			&i.TotalPriceAmountCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsByOrderIDs = `-- name: ListOrderItemsByOrderIDs :many
SELECT order_id, item_position, product_id, sku, product_name, quantity, unit_price_currency, unit_price_amount_cents, total_price_currency, total_price_amount_cents
FROM order_items
WHERE order_id = ANY($1::text[])
ORDER BY order_id ASC, item_position ASC
`

func (q *Queries) ListOrderItemsByOrderIDs(ctx context.Context, dollar_1 []string) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrderIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.OrderID,
			&i.ItemPosition,
			&i.ProductID,
			&i.Sku,
			&i.ProductName,
			&i.Quantity,
			&i.UnitPriceCurrency,
			&i.UnitPriceAmountCents,
			&i.TotalPriceCurrency,
			&i.TotalPriceAmountCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByCustomer = `-- name: ListOrdersByCustomer :many
SELECT id, customer_id, idempotency_key, total_amount_currency, total_amount_cents, status, shipping_country, shipping_city, shipping_street, shipping_postal_code, shipping_house, shipping_apartment, payment_method, payment_method_details, cancel_reason, created_at, updated_at
FROM orders
WHERE customer_id = $1
ORDER BY created_at ASC, id ASC
LIMIT $2 OFFSET $3
`

type ListOrdersByCustomerParams struct {
	CustomerID string `json:"customer_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) ListOrdersByCustomer(ctx context.Context, arg ListOrdersByCustomerParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByCustomer, arg.CustomerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.IdempotencyKey,
			&i.TotalAmountCurrency,
			&i.TotalAmountCents,
			&i.Status,
			&i.ShippingCountry,
			&i.ShippingCity,
			&i.ShippingStreet,
			&i.ShippingPostalCode,
			&i.ShippingHouse,
			&i.ShippingApartment,
			&i.PaymentMethod,
			&i.PaymentMethodDetails,
			&i.CancelReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrderOutboxEventPublished = `-- name: MarkOrderOutboxEventPublished :exec
UPDATE order_outbox_events
SET
    published_at = $2,
    locked_at = NULL,
    last_error = ''
WHERE id = $1
`

type MarkOrderOutboxEventPublishedParams struct {
	ID          string             `json:"id"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) MarkOrderOutboxEventPublished(ctx context.Context, arg MarkOrderOutboxEventPublishedParams) error {
	_, err := q.db.Exec(ctx, markOrderOutboxEventPublished, arg.ID, arg.PublishedAt)
	return err
}

const releaseOrderOutboxEvent = `-- name: ReleaseOrderOutboxEvent :exec
UPDATE order_outbox_events
SET
    locked_at = NULL,
    attempt_count = attempt_count + 1,
    last_error = $2
WHERE id = $1
`

type ReleaseOrderOutboxEventParams struct {
	ID        string `json:"id"`
	LastError string `json:"last_error"`
}

func (q *Queries) ReleaseOrderOutboxEvent(ctx context.Context, arg ReleaseOrderOutboxEventParams) error {
	_, err := q.db.Exec(ctx, releaseOrderOutboxEvent, arg.ID, arg.LastError)
	return err
}

const updateOrder = `-- name: UpdateOrder :one
UPDATE orders
SET
    customer_id = $2,
    idempotency_key = $3,
    total_amount_currency = $4,
    total_amount_cents = $5,
    status = $6,
    shipping_country = $7,
    shipping_city = $8,
    shipping_street = $9,
    shipping_postal_code = $10,
    shipping_house = $11,
    shipping_apartment = $12,
    payment_method = $13,
    payment_method_details = $14,
    cancel_reason = $15,
    created_at = $16,
    updated_at = $17
WHERE id = $1
RETURNING id, customer_id, idempotency_key, total_amount_currency, total_amount_cents, status, shipping_country, shipping_city, shipping_street, shipping_postal_code, shipping_house, shipping_apartment, payment_method, payment_method_details, cancel_reason, created_at, updated_at
`

type UpdateOrderParams struct {
	ID                   string             `json:"id"`
	CustomerID           string             `json:"customer_id"`
	IdempotencyKey       pgtype.Text        `json:"idempotency_key"`
	TotalAmountCurrency  string             `json:"total_amount_currency"`
	TotalAmountCents     int64              `json:"total_amount_cents"`
	Status               string             `json:"status"`
	ShippingCountry      string             `json:"shipping_country"`
	ShippingCity         string             `json:"shipping_city"`
	ShippingStreet       string             `json:"shipping_street"`
	ShippingPostalCode   string             `json:"shipping_postal_code"`
	ShippingHouse        string             `json:"shipping_house"`
	ShippingApartment    string             `json:"shipping_apartment"`
	PaymentMethod        string             `json:"payment_method"`
	PaymentMethodDetails string             `json:"payment_method_details"`
	CancelReason         string             `json:"cancel_reason"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrder,
		arg.ID,
		arg.CustomerID,
		arg.IdempotencyKey,
		arg.TotalAmountCurrency,
		arg.TotalAmountCents,
		arg.Status,
		arg.ShippingCountry,
		arg.ShippingCity,
		arg.ShippingStreet,
		arg.ShippingPostalCode,
		arg.ShippingHouse,
		arg.ShippingApartment,
		arg.PaymentMethod,
		arg.PaymentMethodDetails,
		arg.CancelReason,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.IdempotencyKey,
		&i.TotalAmountCurrency,
		&i.TotalAmountCents,
		&i.Status,
		&i.ShippingCountry,
		&i.ShippingCity,
		&i.ShippingStreet,
		&i.ShippingPostalCode,
		&i.ShippingHouse,
		&i.ShippingApartment,
		&i.PaymentMethod,
		&i.PaymentMethodDetails,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
