// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package paymentdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Payment struct {
	ID                   string             `json:"id"`
	OrderID              string             `json:"order_id"`
	CustomerID           string             `json:"customer_id"`
	AmountCurrency       string             `json:"amount_currency"`
	AmountCents          int64              `json:"amount_cents"`
	PaymentMethod        string             `json:"payment_method"`
	PaymentMethodDetails string             `json:"payment_method_details"`
	IdempotencyKey       pgtype.Text        `json:"idempotency_key"`
	Status               string             `json:"status"`
	CancelReason         string             `json:"cancel_reason"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}
