// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment.sql

package paymentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPaymentsByCustomer = `-- name: CountPaymentsByCustomer :one
SELECT COUNT(*)
FROM payments
WHERE customer_id = $1
`

func (q *Queries) CountPaymentsByCustomer(ctx context.Context, customerID string) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentsByCustomer, customerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    id,
    order_id,
    customer_id,
    amount_currency,
    amount_cents,
    payment_method,
    payment_method_details,
    idempotency_key,
    status,
    cancel_reason,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, order_id, customer_id, amount_currency, amount_cents, payment_method, payment_method_details, idempotency_key, status, cancel_reason, created_at, updated_at
`

type CreatePaymentParams struct {
	ID                   string             `json:"id"`
	OrderID              string             `json:"order_id"`
	CustomerID           string             `json:"customer_id"`
	AmountCurrency       string             `json:"amount_currency"`
	AmountCents          int64              `json:"amount_cents"`
	PaymentMethod        string             `json:"payment_method"`
	PaymentMethodDetails string             `json:"payment_method_details"`
	IdempotencyKey       pgtype.Text        `json:"idempotency_key"`
	Status               string             `json:"status"`
	CancelReason         string             `json:"cancel_reason"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ID,
		arg.OrderID,
		arg.CustomerID,
		arg.AmountCurrency,
		arg.AmountCents,
		arg.PaymentMethod,
		arg.PaymentMethodDetails,
		arg.IdempotencyKey,
		arg.Status,
		arg.CancelReason,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.CustomerID,
		&i.AmountCurrency,
		&i.AmountCents,
		&i.PaymentMethod,
		&i.PaymentMethodDetails,
		&i.IdempotencyKey,
		&i.Status,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, order_id, customer_id, amount_currency, amount_cents, payment_method, payment_method_details, idempotency_key, status, cancel_reason, created_at, updated_at
FROM payments
WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.CustomerID,
		&i.AmountCurrency,
		&i.AmountCents,
		&i.PaymentMethod,
		&i.PaymentMethodDetails,
		&i.IdempotencyKey,
		&i.Status,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByIdempotencyKey = `-- name: GetPaymentByIdempotencyKey :one
SELECT id, order_id, customer_id, amount_currency, amount_cents, payment_method, payment_method_details, idempotency_key, status, cancel_reason, created_at, updated_at
FROM payments
WHERE idempotency_key = $1
`

func (q *Queries) GetPaymentByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByIdempotencyKey, idempotencyKey)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.CustomerID,
		&i.AmountCurrency,
		&i.AmountCents,
		&i.PaymentMethod,
		&i.PaymentMethodDetails,
		&i.IdempotencyKey,
		&i.Status,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByOrderID = `-- name: GetPaymentByOrderID :one
SELECT id, order_id, customer_id, amount_currency, amount_cents, payment_method, payment_method_details, idempotency_key, status, cancel_reason, created_at, updated_at
FROM payments
WHERE order_id = $1
`

func (q *Queries) GetPaymentByOrderID(ctx context.Context, orderID string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByOrderID, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.CustomerID,
		&i.AmountCurrency,
		&i.AmountCents,
		&i.PaymentMethod,
		&i.PaymentMethodDetails,
		&i.IdempotencyKey,
		&i.Status,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentsByCustomer = `-- name: ListPaymentsByCustomer :many
SELECT id, order_id, customer_id, amount_currency, amount_cents, payment_method, payment_method_details, idempotency_key, status, cancel_reason, created_at, updated_at
FROM payments
WHERE customer_id = $1
ORDER BY created_at ASC, id ASC
LIMIT $2 OFFSET $3
`

type ListPaymentsByCustomerParams struct {
	CustomerID string `json:"customer_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) ListPaymentsByCustomer(ctx context.Context, arg ListPaymentsByCustomerParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByCustomer, arg.CustomerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.CustomerID,
			&i.AmountCurrency,
			&i.AmountCents,
			&i.PaymentMethod,
			&i.PaymentMethodDetails,
			&i.IdempotencyKey,
			&i.Status,
			&i.CancelReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePayment = `-- name: UpdatePayment :one
UPDATE payments
SET
    order_id = $2,
    customer_id = $3,
    amount_currency = $4,
    amount_cents = $5,
    payment_method = $6,
    payment_method_details = $7,
    idempotency_key = $8,
    status = $9,
    cancel_reason = $10,
    created_at = $11,
    updated_at = $12
WHERE id = $1
RETURNING id, order_id, customer_id, amount_currency, amount_cents, payment_method, payment_method_details, idempotency_key, status, cancel_reason, created_at, updated_at
`

type UpdatePaymentParams struct {
	ID                   string             `json:"id"`
	OrderID              string             `json:"order_id"`
	CustomerID           string             `json:"customer_id"`
	AmountCurrency       string             `json:"amount_currency"`
	AmountCents          int64              `json:"amount_cents"`
	PaymentMethod        string             `json:"payment_method"`
	PaymentMethodDetails string             `json:"payment_method_details"`
	IdempotencyKey       pgtype.Text        `json:"idempotency_key"`
	Status               string             `json:"status"`
	CancelReason         string             `json:"cancel_reason"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePayment,
		arg.ID,
		arg.OrderID,
		arg.CustomerID,
		arg.AmountCurrency,
		arg.AmountCents,
		arg.PaymentMethod,
		arg.PaymentMethodDetails,
		arg.IdempotencyKey,
		arg.Status,
		arg.CancelReason,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.CustomerID,
		&i.AmountCurrency,
		&i.AmountCents,
		&i.PaymentMethod,
		&i.PaymentMethodDetails,
		&i.IdempotencyKey,
		&i.Status,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
