// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package inventorydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInventoryStock = `-- name: CreateInventoryStock :one
INSERT INTO inventory_stocks (
    product_id,
    available_quantity,
    reserved_quantity,
    total_quantity,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING product_id, available_quantity, reserved_quantity, total_quantity, created_at, updated_at
`

type CreateInventoryStockParams struct {
	ProductID         string             `json:"product_id"`
	AvailableQuantity int64              `json:"available_quantity"`
	ReservedQuantity  int64              `json:"reserved_quantity"`
	TotalQuantity     int64              `json:"total_quantity"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateInventoryStock(ctx context.Context, arg CreateInventoryStockParams) (InventoryStock, error) {
	row := q.db.QueryRow(ctx, createInventoryStock,
		arg.ProductID,
		arg.AvailableQuantity,
		arg.ReservedQuantity,
		arg.TotalQuantity,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i InventoryStock
	err := row.Scan(
		&i.ProductID,
		&i.AvailableQuantity,
		&i.ReservedQuantity,
		&i.TotalQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInventoryReservation = `-- name: DeleteInventoryReservation :exec
DELETE FROM inventory_reservations
WHERE product_id = $1
  AND order_id = $2
`

type DeleteInventoryReservationParams struct {
	ProductID string `json:"product_id"`
	OrderID   string `json:"order_id"`
}

func (q *Queries) DeleteInventoryReservation(ctx context.Context, arg DeleteInventoryReservationParams) error {
	_, err := q.db.Exec(ctx, deleteInventoryReservation, arg.ProductID, arg.OrderID)
	return err
}

const getReservationByProductIDAndOrderID = `-- name: GetReservationByProductIDAndOrderID :one
SELECT product_id, order_id, quantity, created_at, updated_at
FROM inventory_reservations
WHERE product_id = $1
  AND order_id = $2
`

type GetReservationByProductIDAndOrderIDParams struct {
	ProductID string `json:"product_id"`
	OrderID   string `json:"order_id"`
}

func (q *Queries) GetReservationByProductIDAndOrderID(ctx context.Context, arg GetReservationByProductIDAndOrderIDParams) (InventoryReservation, error) {
	row := q.db.QueryRow(ctx, getReservationByProductIDAndOrderID, arg.ProductID, arg.OrderID)
	var i InventoryReservation
	err := row.Scan(
		&i.ProductID,
		&i.OrderID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservationByProductIDAndOrderIDForUpdate = `-- name: GetReservationByProductIDAndOrderIDForUpdate :one
SELECT product_id, order_id, quantity, created_at, updated_at
FROM inventory_reservations
WHERE product_id = $1
  AND order_id = $2
FOR UPDATE
`

type GetReservationByProductIDAndOrderIDForUpdateParams struct {
	ProductID string `json:"product_id"`
	OrderID   string `json:"order_id"`
}

func (q *Queries) GetReservationByProductIDAndOrderIDForUpdate(ctx context.Context, arg GetReservationByProductIDAndOrderIDForUpdateParams) (InventoryReservation, error) {
	row := q.db.QueryRow(ctx, getReservationByProductIDAndOrderIDForUpdate, arg.ProductID, arg.OrderID)
	var i InventoryReservation
	err := row.Scan(
		&i.ProductID,
		&i.OrderID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStockByProductID = `-- name: GetStockByProductID :one
SELECT product_id, available_quantity, reserved_quantity, total_quantity, created_at, updated_at
FROM inventory_stocks
WHERE product_id = $1
`

func (q *Queries) GetStockByProductID(ctx context.Context, productID string) (InventoryStock, error) {
	row := q.db.QueryRow(ctx, getStockByProductID, productID)
	var i InventoryStock
	err := row.Scan(
		&i.ProductID,
		&i.AvailableQuantity,
		&i.ReservedQuantity,
		&i.TotalQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStockByProductIDForUpdate = `-- name: GetStockByProductIDForUpdate :one
SELECT product_id, available_quantity, reserved_quantity, total_quantity, created_at, updated_at
FROM inventory_stocks
WHERE product_id = $1
FOR UPDATE
`

func (q *Queries) GetStockByProductIDForUpdate(ctx context.Context, productID string) (InventoryStock, error) {
	row := q.db.QueryRow(ctx, getStockByProductIDForUpdate, productID)
	var i InventoryStock
	err := row.Scan(
		&i.ProductID,
		&i.AvailableQuantity,
		&i.ReservedQuantity,
		&i.TotalQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseInventoryStock = `-- name: ReleaseInventoryStock :one
UPDATE inventory_stocks
SET
    available_quantity = available_quantity + $2,
    reserved_quantity = reserved_quantity - $2,
    updated_at = $3
WHERE product_id = $1
  AND reserved_quantity >= $2
RETURNING product_id, available_quantity, reserved_quantity, total_quantity, created_at, updated_at
`

type ReleaseInventoryStockParams struct {
	ProductID         string             `json:"product_id"`
	AvailableQuantity int64              `json:"available_quantity"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ReleaseInventoryStock(ctx context.Context, arg ReleaseInventoryStockParams) (InventoryStock, error) {
	row := q.db.QueryRow(ctx, releaseInventoryStock, arg.ProductID, arg.AvailableQuantity, arg.UpdatedAt)
	var i InventoryStock
	err := row.Scan(
		&i.ProductID,
		&i.AvailableQuantity,
		&i.ReservedQuantity,
		&i.TotalQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reserveInventoryStock = `-- name: ReserveInventoryStock :one
UPDATE inventory_stocks
SET
    available_quantity = available_quantity - $2,
    reserved_quantity = reserved_quantity + $2,
    updated_at = $3
WHERE product_id = $1
  AND available_quantity >= $2
RETURNING product_id, available_quantity, reserved_quantity, total_quantity, created_at, updated_at
`

type ReserveInventoryStockParams struct {
	ProductID         string             `json:"product_id"`
	AvailableQuantity int64              `json:"available_quantity"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ReserveInventoryStock(ctx context.Context, arg ReserveInventoryStockParams) (InventoryStock, error) {
	row := q.db.QueryRow(ctx, reserveInventoryStock, arg.ProductID, arg.AvailableQuantity, arg.UpdatedAt)
	var i InventoryStock
	err := row.Scan(
		&i.ProductID,
		&i.AvailableQuantity,
		&i.ReservedQuantity,
		&i.TotalQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInventoryReservationQuantity = `-- name: UpdateInventoryReservationQuantity :exec
UPDATE inventory_reservations
SET
    quantity = $3,
    updated_at = $4
WHERE product_id = $1
  AND order_id = $2
`

type UpdateInventoryReservationQuantityParams struct {
	ProductID string             `json:"product_id"`
	OrderID   string             `json:"order_id"`
	Quantity  int64              `json:"quantity"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateInventoryReservationQuantity(ctx context.Context, arg UpdateInventoryReservationQuantityParams) error {
	_, err := q.db.Exec(ctx, updateInventoryReservationQuantity,
		arg.ProductID,
		arg.OrderID,
		arg.Quantity,
		arg.UpdatedAt,
	)
	return err
}

const upsertInventoryReservation = `-- name: UpsertInventoryReservation :exec
INSERT INTO inventory_reservations (
    product_id,
    order_id,
    quantity,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (product_id, order_id)
DO UPDATE
SET
    quantity = inventory_reservations.quantity + EXCLUDED.quantity,
    updated_at = EXCLUDED.updated_at
`

type UpsertInventoryReservationParams struct {
	ProductID string             `json:"product_id"`
	OrderID   string             `json:"order_id"`
	Quantity  int64              `json:"quantity"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertInventoryReservation(ctx context.Context, arg UpsertInventoryReservationParams) error {
	_, err := q.db.Exec(ctx, upsertInventoryReservation,
		arg.ProductID,
		arg.OrderID,
		arg.Quantity,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
