// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package inventorydb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InventoryReservation struct {
	ProductID string             `json:"product_id"`
	OrderID   string             `json:"order_id"`
	Quantity  int64              `json:"quantity"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type InventoryStock struct {
	ProductID         string             `json:"product_id"`
	AvailableQuantity int64              `json:"available_quantity"`
	ReservedQuantity  int64              `json:"reserved_quantity"`
	TotalQuantity     int64              `json:"total_quantity"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}
